### ISSUE TITLE
pretrained weights for the backbone

### ISSUE THREAD

**Issue by harrytea** [JerryX1110/RPCMVOS#10]
Hi, the pretrained weights file named "resnet101-deeplabv3p.pth.tar" for the backbone is missing.

**Comment by JerryX1110** [comment]
Thanks for your interest in our work! However, I am sorry to say that the link is maintained by the user of other repos. And I could not have access to this file right now the same as you.

My suggestion is that you can search for the pre-trained weights of ResNet101 backbone in the official DeepLabV3+ repo (https://github.com/jfzhang95/pytorch-deeplab-xception). If you still could not find a pre-trained weight for the backbone, you can directly train the whole model from scratch because I empirically find that the pre-training will not make a big difference in the final performance.

**Comment by JerryX1110** [comment]
> Hi, the pretrained weights file named "resnet101-deeplabv3p.pth.tar" for the backbone is missing.

I am trying to find someone who has downloaded and kept the pre-trained weights file. Please stay tuned and I will notice you as soon as I get it.

**Comment by harrytea** [comment]
> > Hi, the pretrained weights file named "resnet101-deeplabv3p.pth.tar" for the backbone is missing.
> 
> I am trying to find someone who has downloaded and kept the pre-trained weights file. Please stay tuned and I will notice you as soon as I get it.

I have found it from DeepLabV3 rep, thanks~ ^-^

**Comment by JerryX1110** [comment]
That sounds nice. 👍
