### ISSUE TITLE
About multi-scale testing

### ISSUE THREAD

**Issue by longmalongma** [JerryX1110/RPCMVOS#2]
Hello, thank you very much for your great work. Can you provide your multi-scale test code?

**Comment by JerryX1110** [comment]
Thanks! Due to the policy in the company, I can't share the code with you right now. After a code review in my company, I will release it asap.  Specifically, we follow the multi-scale evaluation method as CFBI and directly average the probability map of several scales. Then, we use an argmax function for the final ensemble.  

By the way, you can find that the multi-scale testing only brings a minor gain for our model. I think simply conducting an averaging operation is not an optimal way for the ensemble.

**Comment by longmalongma** [comment]
> 

Ok, thanks! Looking forward to your code!
