### ISSUE TITLE
model inference

### ISSUE THREAD

**Issue by Xianhua-He** [JerryX1110/RPCMVOS#7]
Hello, is it convenient to provide the model weight file(save_step_400000.pth)? I want to try to inference the model and see the effect.

**Comment by JerryX1110** [comment]
Thanks for your interest on our work. As I am currently not an intern at MSRA, I do not have the access to get my checkpoint files on the AZURE Blob right now (due to some privacy or commercial issues).

The recomputed results on both YouTube-VOS18/19 and DAVIS17 Val/Test-dev are available on [Google Drive](https://drive.google.com/drive/folders/1RaffnMvmQF4Nct30UBXqwrfOXTZ8rvQf?usp=sharing) and [Baidu Disk](https://pan.baidu.com/s/1WqB-SsbT7W-a6DbLIz8Lzw) (BaiduDisk password:6666).

And you can have a look on the qualitative results. 

=============================================================================
By the way, I have a experiment-version code base and model weight files (not compatible with the code base in this repo) which can reproduce the results in my paper. 

However, it needs some time to clear and organize that code. As I am currently busy with my new research, maybe the earliest time that I can share with you is about next month. Sorry for that~
